GET http://localhost:3000/recipes.json



###
GET http://localhost:3000/recipes/113


###
POST http://localhost:3000/recipes.json
content-type: application/json

{
  "input_chef": "Rachel Ray",
  "input_title": "falafel",
  "input_ingredients": "chickpeas, bread, spices",
  "input_directions": "put in blender, and fry",
  "input_prep_time": 100,
  "input_image_url": "https://www.thespruceeats.com/thmb/I75OB9paT-KRF4Q64kXFaLMH27w=/3000x2000/filters:fill(auto,1)/what-is-falafel-2355693-Hero_01-ba33428ae8704932ba4e43b526bb81ff.jpg"
}


###
PATCH http://localhost:3000/recipes/115.json
content-type: application/json

{
  "input_prep_time": 50
}

###
DELETE http://localhost:3000/recipes/116


###
POST http://localhost:3000/users
content-type: application/json

{
  "name": "leslie",
  "email": "leslie@pawnee.us",
  "password": "password",
  "password_digest": "password"
}

###
POST http://localhost:3000/sessions
content-type: application/json

{
  "email": "bob@bob.com",
  "password": "password"
}